# 数据库连接池池配置
spring:
  datasource:
    # 8.0
    driver-class-name: com.mysql.cj.jdbc.Driver
    # \u6570\u636E\u5E93\u5730\u5740\uFF0C useSSL: \u4E0D\u4F7F\u7528\u5B89\u5168\u5957\u63A5\u5B57   serverTimeZone: \u65F6\u533A
    # 8.0 \u4EE5\u4E0A\u7684\u9A71\u52A8\u5199\u6CD5\u5982\u4E0B
    url: jdbc:mysql://localhost:3306/dailycost?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456